import type { Metadata } from "next";
import "./globals.css";
import { dbConnect } from "../lib/dbConnect";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await dbConnect();
  return (

    <html lang="en">
      <body className={'h-screen w-screen  bg-[#1d1c20] text-white'}><main className="max-w-[1000px] mx-auto p-10">{children}</main></body>
      <Toaster />
    </html>
  );
}
